### ISSUE TITLE
I wonder where I can use build_database.py?

### ISSUE THREAD

**Issue by HyeokJaeKiM** [opera-adt/burst_db#24]
Thanks for reading my quetion.

I want to make sqlite for my sentinel-1 image

so I'm trying follow your steps

but I can not find where is build_database.py

**Comment by scottstanie** [comment]
Sorry for the out of date instructions. The updated readme should help, you just have to install it and run `opera-db create`

**Comment by HyeokJaeKiM** [comment]
Thank you sir

As you mentioned, If I downloaded the conda-forge package, I can use
"opera-db"??

but there isn't "opera-db" command

please let me know sir!

2024년 1월 19일 (금) 오전 9:09, Scott Staniewicz ***@***.***>님이 작성:

**Comment by scottstanie** [comment]
Just clarifying that this isn't on conda forge or pypi- it would have to be installed locally to make by cloning then running `pip install .`

**Comment by HyeokJaeKiM** [comment]
Thank you sir!

Can I ask you one more question?

< I already questioned you like below on opera-adt compass >

I want to make a CSLC image in my interest region

so I try to make " s1_cslc_geo.yaml " ---picture 1

but I got a error. I guess the reason is due to burst_database_file missing
--picture 2

So I try to do " burst_db " that you gave us. I finished doing "
opera-db-create " --picture3

but I don't know how to use them files that I made after doing "
opera-db-create "

Could you answer me ① how to make a " burst_database_file "
and If my way is correct, ② how to make a "burst_database_file in "
burst_db in github "




2024년 1월 20일 (토) 오전 12:01, Scott Staniewicz ***@***.***>님이 작성:
