### ISSUE TITLE
Consistent CSLC database generation improvements: filter HH, add `generation_datetime`

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/burst_db#42]
The CMR survey has HH, as well as VV. We should add a filter to ignore HH, rather than remove it from the CMR survey

@philipjyoon 

> Also we should add one more date to the file name. Currently we have two dates in the file name of the db file: start and end of the data date. But we should add 3rd date which is the date at which the db file was generated. I did that for the file that I modified this weekend

**Comment by philipjyoon** [comment]
@scottstanie while I'm making suggestions, here is one more: can we prettify the output of the json file? Currently the entire content is in a single line and makes it difficult to view/edit. People could prettify in the text editor but sometimes that crashes the text editor, takes a long time, gets redundant, etc.

**Comment by scottstanie** [comment]
Sure thing 👍  I first had it like that to save space, but prettified it's only 7.9MB vs 5.9MB in the unreadable format
