### ISSUE TITLE
Across-track EPSG constraint

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/burst_db#5]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

One of the points discussed in the PR #2 was about the across-track constraint of EPSG, which is to use the same map projection for the IW1/2/3 bursts on the same track. The reason behind this constraint is to make the along-track bursts more stitch-friendly (i.e. no reproduction necessary). One of the concerns that has been made was that it might cause the EPSG changes along-track to be less related to what it is across track.

One of the ways to investigate the influence of the EPSG constraint is to detect the number of EPSG changes along track from the DB generated with / without the constraint.

### What did you expect?

1. Get the DB **with** the across-track EPSG constraint
2. Get the DB **without** the across-track EPSG constraint
3. Follow the data along track and detect the EPSG change
4. Compare the number

**Comment by scottstanie** [comment]
note that this will be changed in #8 since all bursts within a frame will get the same EPSG assigned
